In [2]:
import pandas as pd

In [9]:
# 데이터 불러오기
# 데이터 전처리 - 좋아요 누른 노래 개수 10개 이상, 1500개 이하인 유저의 노래 목록 수집
# 목록에서 좋아요 누른 사람이 한명인 노래 제거 + 비어있는 데이터 제거
data=pd.read_csv('./Datasets/likelist3.csv')
data.columns = ['user_id', 'title', 'artist','album','title_artist','quantity']
data

,user_id,title,artist,album,title_artist,quantity
0,38795083,STAY,The Kid LAROI,Stay,STAY_The Kid LAROI,1
1,38795083,abcdefu,GAYLE,abcdefu,abcdefu_GAYLE,1
2,38795083,폰서트,10CM,4.0,폰서트_10CM,1
3,38795083,pet,10CM,4.0,pet_10CM,1
4,38795083,그라데이션,10CM,5.3,그라데이션_10CM,1
...,...,...,...,...,...,...
169942,46865104,그대라는 사치,임영웅,사랑의 콜센타 PART62,그대라는 사치_임영웅,1
169943,46865104,별빛 같은 나의 사랑아,임영웅,별빛 같은 나의 사랑아,별빛 같은 나의 사랑아_임영웅,1
169944,46865104,이제 나만 믿어요,임영웅,내일은 미스터트롯 우승자 특전곡,이제 나만 믿어요_임영웅,1
169945,46865104,사랑은 늘 도망가,임영웅,신사와 아가씨 OST Part.2,사랑은 늘 도망가_임영웅,1
169946,46865104,목로주점 (MR),임영웅,사랑의 콜센타 PART50,목로주점 (MR)_임영웅,1

In [10]:
# 사용하는 column들만 남기기
using_cols = ['user_id', 'title_artist', 'quantity']
data1 = data[using_cols]
data1

         user_id        title_artist  quantity
0       38795083  STAY_The Kid LAROI         1
1       38795083       abcdefu_GAYLE         1
2       38795083            폰서트_10CM         1
3       38795083            pet_10CM         1
4       38795083          그라데이션_10CM         1
...          ...                 ...       ...
169942  46865104         그대라는 사치_임영웅         1
169943  46865104    별빛 같은 나의 사랑아_임영웅         1
169944  46865104       이제 나만 믿어요_임영웅         1
169945  46865104       사랑은 늘 도망가_임영웅         1
169946  46865104       목로주점 (MR)_임영웅         1

[169947 rows x 3 columns]

In [11]:
print(data1['user_id'].nunique())   # 999명의 유저
print(data1['title_artist'].nunique())     #24079개 노래

999
24079

In [12]:
# 좋아요 목록에 가장 많이 등장한 노래 알아보기
title_count = data1.groupby('title_artist')['user_id'].count()
title_count.sort_values(ascending=False)

title_artist
Dynamite_방탄소년단                                     178
작은 것들을 위한 시 (Boy With Luv) (Feat. Halsey)_방탄소년단    171
에잇(Prod.&Feat. SUGA of BTS)_아이유                    154
밤편지_아이유                                            146
봄날_방탄소년단                                           142
                                                  ...
미안해서 미안해 (Feat. 권정열 of 10cm)_펀치넬로 (punchnello)       2
미안해야 하는거니_애즈원                                        2
미완예찬 (未完禮讚)_버즈                                       2
Pour Ma Soeur En Allee_Andre Gagnon                  2
!!! (Prod. Lnb)_래원 (Layone)                          2
Name: user_id, Length: 24079, dtype: int64

In [22]:
# 내 음악 데이터 만들기
user_dict = {}

def my_music_list(music):
    global user_dict
    user_dict[music] = 1

    return user_dict

def searching_music(music):
    music_df = pd.DataFrame(list(set(zip(data1['title_artist']))), columns = ['title_artist'])
    music_df = music_df[music_df['title_artist'].map(lambda x : music in x)]

    return music_df

In [66]:
# 노래, 가수 검색
music = "Save Your Tears (Remix)_The Weeknd" 
searching_music(music)

                                            title_artist
8696   Save Your Tears (Remix)_The Weeknd, Ariana Grande
22296                 Save Your Tears (Remix)_The Weeknd

In [24]:
#노래,가수 검색을 통한 내 음악 데이터 생성
your_name = '손정용'
my_music_list('맨정신_BIGBANG (빅뱅)')
my_music_list('strawberry moon_아이유')
my_music_list('Hype boy_NewJeans')
my_music_list('시간과 낙엽_AKMU (악뮤)')
my_music_list('200%_AKMU (악뮤)')
my_music_list('너에게 난, 나에게 넌_미도와 파라솔')
my_music_list('Circles_Post Malone')
my_music_list('Ghost_Justin Bieber')
my_music_list('Strawberries & Cigarettes_Troye Sivan')
my_music_list('Save Your Tears (Remix)_The Weeknd')
my_music_list('Crazy AF_In Real Life')
my_music_list('이 지금_아이유')
my_music_list('사랑인가 봐_멜로망스')
my_music_list('Christmas Tree_V')
my_music_list('애상_쿨 (COOL)')
my_music_list('STUPID LIAR_BIGBANG (빅뱅)')
my_music_list('소년이여_G-DRAGON')
my_music_list('사랑하기 때문에_유재하')
my_music_list('Lonely Night_권진아')
my_music_list('Dynamite_방탄소년단')

{'맨정신_BIGBANG (빅뱅)': 1,
 'strawberry moon_아이유': 1,
 'Hype boy_NewJeans': 1,
 '시간과 낙엽_AKMU (악뮤)': 1,
 '200%_AKMU (악뮤)': 1,
 '너에게 난, 나에게 넌_미도와 파라솔': 1,
 'Circles_Post Malone': 1,
 'Ghost_Justin Bieber': 1,
 'Strawberries & Cigarettes_Troye Sivan': 1,
 'Save Your Tears (Remix)_The Weeknd': 1,
 'Crazy AF_In Real Life': 1,
 '이 지금_아이유': 1,
 '사랑인가 봐_멜로망스': 1,
 'Christmas Tree_V': 1,
 '애상_쿨 (COOL)': 1,
 'STUPID LIAR_BIGBANG (빅뱅)': 1,
 '소년이여_G-DRAGON': 1,
 '사랑하기 때문에_유재하': 1,
 'Lonely Night_권진아': 1,
 'Dynamite_방탄소년단': 1}

In [39]:
my_music_df = pd.DataFrame(zip(user_dict.keys(), user_dict.values()), columns = ['title_artist', 'quantity'])

my_music_df['user_id'] = your_name

data2 = pd.concat([data1, my_music_df])

data2

     user_id              title_artist  quantity
0   38795083        STAY_The Kid LAROI         1
1   38795083             abcdefu_GAYLE         1
2   38795083                  폰서트_10CM         1
3   38795083                  pet_10CM         1
4   38795083                그라데이션_10CM         1
..       ...                       ...       ...
15       손정용  STUPID LIAR_BIGBANG (빅뱅)         1
16       손정용             소년이여_G-DRAGON         1
17       손정용              사랑하기 때문에_유재하         1
18       손정용          Lonely Night_권진아         1
19       손정용            Dynamite_방탄소년단         1

[169967 rows x 3 columns]

In [40]:
# csr matrix 만들기 위해 indexing

# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data2['user_id'].unique()
title_unique = data2['title_artist'].unique()

# 유저, 아티스트 indexing 하는 코드
user_to_idx = {v:k for k,v in enumerate(user_unique)}
title_to_idx = {v:k for k,v in enumerate(title_unique)}

In [41]:
user_to_idx

{38795083: 0,
 60501436: 1,
 43639118: 2,
 23383090: 3,
 54964421: 4,
 54832866: 5,
 38055291: 6,
 42620278: 7,
 9488789: 8,
 41335215: 9,
 15968436: 10,
 46825579: 11,
 51510661: 12,
 27533337: 13,
 50982901: 14,
 29086171: 15,
 39678538: 16,
 33909730: 17,
 34256775: 18,
 38885733: 19,
 12669523: 20,
 28401376: 21,
 56848394: 22,
 58800980: 23,
 52671426: 24,
 42627779: 25,
 49800632: 26,
 39031060: 27,
 44483428: 28,
 1483950: 29,
 20741485: 30,
 28253164: 31,
 55488187: 32,
 56076667: 33,
 29609356: 34,
 45859192: 35,
 43983991: 36,
 8409519: 37,
 3440710: 38,
 40470862: 39,
 492567: 40,
 49589186: 41,
 39226824: 42,
 58137731: 43,
 29197684: 44,
 44316758: 45,
 52058082: 46,
 35344394: 47,
 56955302: 48,
 60276251: 49,
 42775082: 50,
 43094013: 51,
 1537961: 52,
 214868: 53,
 50179619: 54,
 56879590: 55,
 44994678: 56,
 56121461: 57,
 11350808: 58,
 17853245: 59,
 53414994: 60,
 47099753: 61,
 60058043: 62,
 46937681: 63,
 42221851: 64,
 22777643: 65,
 58573152: 66,
 49975724: 67,
 59037572: 68,
 13937021: 69,
 58870679: 70,
 1190807: 71,
 60007878: 72,
 33452794: 73,
 52104893: 74,
 59090210: 75,
 47620400: 76,
 54487830: 77,
 1832194: 78,
 30438097: 79,
 38084434: 80,
 46776416: 81,
 47555771: 82,
 37237092: 83,
 9606273: 84,
 36728258: 85,
 43737801: 86,
 11396057: 87,
 38906307: 88,
 22442399: 89,
 59289325: 90,
 34340366: 91,
 8395371: 92,
 53323987: 93,
 46200220: 94,
 39685945: 95,
 12560030: 96,
 45594444: 97,
 43730800: 98,
 50825937: 99,
 56993314: 100,
 49769113: 101,
 42651295: 102,
 55544717: 103,
 18578108: 104,
 52075699: 105,
 47894003: 106,
 60546413: 107,
 35117703: 108,
 39635936: 109,
 15218723: 110,
 30999551: 111,
 31422353: 112,
 39654918: 113,
 60118372: 114,
 59748880: 115,
 11844624: 116,
 40697684: 117,
 512573: 118,
 15957245: 119,
 17181269: 120,
 58197214: 121,
 43593330: 122,
 50882108: 123,
 20529916: 124,
 54868005: 125,
 41784535: 126,
 52955322: 127,
 26708973: 128,
 54449856: 129,
 47085083: 130,
 51034350: 131,
 55335407: 132,
 11620566: 133,
 56894747: 134,
 38027491: 135,
 39701466: 136,
 60744327: 137,
 55776123: 138,
 38280739: 139,
 59433632: 140,
 48387046: 141,
 50229780: 142,
 55538713: 143,
 38579288: 144,
 24902348: 145,
 52699499: 146,
 49270236: 147,
 36611661: 148,
 15080096: 149,
 38692066: 150,
 38316659: 151,
 53788250: 152,
 49257006: 153,
 58430694: 154,
 59488862: 155,
 58559201: 156,
 7027536: 157,
 53936775: 158,
 60550605: 159,
 42035562: 160,
 58445310: 161,
 49941781: 162,
 29141981: 163,
 58368965: 164,
 5213311: 165,
 49151135: 166,
 5845948: 167,
 22393730: 168,
 48511118: 169,
 40462404: 170,
 28469083: 171,
 37495380: 172,
 55521141: 173,
 35640734: 174,
 48371719: 175,
 35975055: 176,
 33393602: 177,
 56875022: 178,
 13583501: 179,
 38107942: 180,
 52076294: 181,
 58034863: 182,
 58035941: 183,
 51696146: 184,
 58971325: 185,
 34816206: 186,
 46545223: 187,
 26560077: 188,
 34101457: 189,
 17971066: 190,
 43548019: 191,
 15295413: 192,
 51712139: 193,
 9094720: 194,
 59020612: 195,
 44124616: 196,
 54194526: 197,
 37782535: 198,
 36919268: 199,
 39107433: 200,
 42363351: 201,
 21489107: 202,
 50032954: 203,
 4820125: 204,
 60718041: 205,
 37341806: 206,
 50390130: 207,
 22718320: 208,
 46250176: 209,
 37401052: 210,
 27013245: 211,
 42888105: 212,
 44317759: 213,
 54280785: 214,
 4359122: 215,
 36498564: 216,
 52201311: 217,
 39881237: 218,
 32018363: 219,
 45827635: 220,
 34389387: 221,
 31719405: 222,
 25979977: 223,
 19535143: 224,
 48307086: 225,
 60497033: 226,
 38169629: 227,
 17426016: 228,
 40499528: 229,
 14313341: 230,
 53014551: 231,
 36579580: 232,
 41325770: 233,
 41897271: 234,
 58439250: 235,
 44069615: 236,
 28642589: 237,
 35925084: 238,
 52745332: 239,
 48081444: 240,
 46766776: 241,
 30487068: 242,
 39831885: 243,
 38004657: 244,
 46283139: 245,
 30412871: 246,
 23432270: 247,
 41554899: 248,
 40114476: 249,
 47371128: 250,
 60473121: 251,
 41299755: 252,
 38570920: 253,
 52566770: 254,
 30758581: 255,
 26812959: 256,
 42412130: 257,
 5723684: 258,
 31926808: 259,
 39158067: 260,
 45545256: 261,
 44972032: 262,
 45962361: 263,
 2727787: 264,
 41665042: 265,
 3992451: 266,
 51313275: 267,
 598077: 268,
 44509244: 269,
 11625383: 270,
 1122128: 271,
 49430417: 272,
 47301866: 273,
 26468347: 274,
 53098673: 275,
 54935393: 276,
 57264480: 277,
 9064963: 278,
 2311209: 279,
 49640890: 280,
 56589341: 281,
 39337176: 282,
 50416889: 283,
 55553293: 284,
 27099272: 285,
 27410665: 286,
 34823936: 287,
 16826155: 288,
 30126382: 289,
 55850309: 290,
 38272099: 291,
 49042761: 292,
 52710013: 293,
 29682327: 294,
 40061133: 295,
 40762732: 296,
 34210185: 297,
 34041467: 298,
 39830049: 299,
 38538350: 300,
 38158185: 301,
 44747339: 302,
 2892086: 303,
 44526122: 304,
 15037218: 305,
 7345317: 306,
 58415468: 307,
 41083840: 308,
 45733811: 309,
 17520043: 310,
 41309532: 311,
 58106483: 312,
 34140691: 313,
 34102340: 314,
 38313626: 315,
 43012466: 316,
 52584021: 317,
 49576173: 318,
 49769864: 319,
 39301201: 320,
 39703787: 321,
 42519285: 322,
 43581272: 323,
 16510056: 324,
 44913395: 325,
 53632450: 326,
 57641028: 327,
 48552317: 328,
 55646903: 329,
 8855090: 330,
 28689432: 331,
 35359463: 332,
 48216892: 333,
 57270991: 334,
 16025153: 335,
 44156823: 336,
 60726489: 337,
 38904571: 338,
 45488662: 339,
 45871406: 340,
 41919107: 341,
 17007891: 342,
 59774122: 343,
 38375954: 344,
 16436688: 345,
 35700294: 346,
 51069061: 347,
 57238126: 348,
 17277820: 349,
 38089029: 350,
 37962333: 351,
 52467320: 352,
 39052621: 353,
 50739250: 354,
 37615457: 355,
 48144973: 356,
 59336619: 357,
 23096959: 358,
 18580043: 359,
 26000578: 360,
 38682580: 361,
 29095840: 362,
 39258103: 363,
 42231325: 364,
 9975612: 365,
 48423132: 366,
 5209621: 367,
 48551648: 368,
 59791005: 369,
 46207202: 370,
 53484530: 371,
 13940335: 372,
 12487561: 373,
 11025123: 374,
 25194348: 375,
 24118767: 376,
 30678539: 377,
 17323246: 378,
 58806722: 379,
 35417894: 380,
 56092062: 381,
 36940074: 382,
 59343241: 383,
 36233139: 384,
 49967910: 385,
 28619738: 386,
 4356307: 387,
 30796990: 388,
 33680541: 389,
 45268417: 390,
 39113606: 391,
 48279251: 392,
 35674505: 393,
 54271345: 394,
 59575109: 395,
 56401822: 396,
 49895470: 397,
 23712621: 398,
 49139408: 399,
 59370611: 400,
 43355480: 401,
 39626327: 402,
 17193480: 403,
 57657498: 404,
 30905841: 405,
 22468531: 406,
 16274080: 407,
 50052547: 408,
 60297979: 409,
 59780172: 410,
 1296690: 411,
 55174583: 412,
 21956536: 413,
 56384501: 414,
 51521121: 415,
 15906049: 416,
 60591466: 417,
 40875601: 418,
 50315927: 419,
 48190059: 420,
 15249816: 421,
 49124552: 422,
 38054657: 423,
 33113765: 424,
 35966381: 425,
 35394808: 426,
 48645866: 427,
 43060803: 428,
 43617100: 429,
 21681097: 430,
 45234254: 431,
 15532147: 432,
 47993597: 433,
 16214637: 434,
 40778796: 435,
 11401636: 436,
 33949234: 437,
 58070116: 438,
 14054169: 439,
 39388659: 440,
 57798724: 441,
 49762820: 442,
 38627151: 443,
 30575652: 444,
 43731775: 445,
 15169166: 446,
 44579999: 447,
 43694598: 448,
 27686524: 449,
 2873559: 450,
 58549688: 451,
 17311013: 452,
 2783830: 453,
 13159863: 454,
 39763298: 455,
 27691935: 456,
 13972894: 457,
 30798699: 458,
 24002721: 459,
 51363683: 460,
 11597238: 461,
 14706219: 462,
 12076372: 463,
 60649109: 464,
 34517253: 465,
 52002329: 466,
 14562829: 467,
 50357733: 468,
 48188266: 469,
 48489879: 470,
 49773087: 471,
 32102126: 472,
 52909004: 473,
 59944668: 474,
 42571965: 475,
 40350313: 476,
 18601351: 477,
 6873255: 478,
 30566424: 479,
 19989730: 480,
 41584491: 481,
 60462891: 482,
 49082669: 483,
 51321484: 484,
 8724827: 485,
 47266263: 486,
 57362086: 487,
 60115119: 488,
 57537776: 489,
 50620458: 490,
 47245814: 491,
 54951345: 492,
 16017838: 493,
 21595913: 494,
 42267782: 495,
 40128435: 496,
 15236210: 497,
 17590516: 498,
 14236242: 499,
 40679902: 500,
 29496882: 501,
 50058577: 502,
 14604576: 503,
 54759865: 504,
 10578952: 505,
 40552748: 506,
 9770454: 507,
 51951272: 508,
 46260850: 509,
 3306982: 510,
 59215499: 511,
 21565329: 512,
 42445695: 513,
 44333370: 514,
 59427514: 515,
 37582977: 516,
 36574231: 517,
 44818121: 518,
 38196927: 519,
 1592991: 520,
 38056627: 521,
 31118375: 522,
 18045962: 523,
 21265502: 524,
 21609252: 525,
 46633350: 526,
 16854582: 527,
 51064757: 528,
 53241149: 529,
 4092192: 530,
 30810818: 531,
 58855290: 532,
 11008653: 533,
 40969220: 534,
 22233286: 535,
 15374754: 536,
 44773944: 537,
 51569099: 538,
 31434938: 539,
 56476466: 540,
 20886606: 541,
 43905487: 542,
 6255940: 543,
 5303520: 544,
 57478430: 545,
 49870678: 546,
 48660613: 547,
 51118644: 548,
 57057758: 549,
 31444700: 550,
 39203790: 551,
 35428109: 552,
 36972468: 553,
 30282683: 554,
 57051501: 555,
 10287704: 556,
 35737665: 557,
 53823138: 558,
 47338802: 559,
 20753654: 560,
 51016655: 561,
 14645704: 562,
 15770620: 563,
 55239968: 564,
 51865834: 565,
 35668034: 566,
 53990246: 567,
 60577924: 568,
 45003663: 569,
 58127167: 570,
 11026559: 571,
 34115767: 572,
 3734889: 573,
 33398863: 574,
 18799220: 575,
 48676973: 576,
 60799327: 577,
 47140298: 578,
 10987023: 579,
 21421468: 580,
 44026346: 581,
 51996448: 582,
 7348215: 583,
 49656798: 584,
 55630866: 585,
 52967756: 586,
 51485098: 587,
 52740421: 588,
 9384178: 589,
 37918317: 590,
 40736649: 591,
 60776337: 592,
 38229396: 593,
 51142821: 594,
 31104753: 595,
 33631899: 596,
 46057092: 597,
 54878690: 598,
 40643088: 599,
 34798170: 600,
 26984134: 601,
 38171372: 602,
 39773153: 603,
 58159397: 604,
 18662379: 605,
 47042781: 606,
 58994478: 607,
 28208333: 608,
 36307143: 609,
 38006872: 610,
 45057808: 611,
 16945384: 612,
 19768950: 613,
 49195067: 614,
 52955166: 615,
 60190894: 616,
 7405890: 617,
 57335702: 618,
 16563477: 619,
 35676305: 620,
 50677375: 621,
 51504273: 622,
 14967469: 623,
 44843898: 624,
 38690925: 625,
 57374075: 626,
 10721360: 627,
 55200534: 628,
 29584063: 629,
 50135869: 630,
 46818193: 631,
 43056883: 632,
 44976160: 633,
 5513567: 634,
 36632270: 635,
 55195773: 636,
 30735423: 637,
 14529018: 638,
 39775124: 639,
 7804212: 640,
 57477884: 641,
 29368839: 642,
 58036963: 643,
 41281749: 644,
 24037905: 645,
 59699588: 646,
 40229917: 647,
 55021356: 648,
 38184955: 649,
 53824122: 650,
 55180973: 651,
 42435892: 652,
 48287088: 653,
 20771196: 654,
 53706867: 655,
 48551873: 656,
 55475106: 657,
 40621604: 658,
 60191415: 659,
 46850735: 660,
 43392429: 661,
 58781981: 662,
 50108585: 663,
 30520894: 664,
 43743638: 665,
 35126461: 666,
 49583096: 667,
 6340506: 668,
 58269936: 669,
 5338288: 670,
 36516112: 671,
 48678750: 672,
 44208117: 673,
 29711228: 674,
 46011316: 675,
 8859180: 676,
 58890107: 677,
 451861: 678,
 48410980: 679,
 44610687: 680,
 46989382: 681,
 31915792: 682,
 39030967: 683,
 35911951: 684,
 3080984: 685,
 55924393: 686,
 15991573: 687,
 53960985: 688,
 58600150: 689,
 52984374: 690,
 30409397: 691,
 48863811: 692,
 39930618: 693,
 1906897: 694,
 17747774: 695,
 5785710: 696,
 50186178: 697,
 30401215: 698,
 23766977: 699,
 46958121: 700,
 39194676: 701,
 43762973: 702,
 35736902: 703,
 9252214: 704,
 57961647: 705,
 60259568: 706,
 39597578: 707,
 53043510: 708,
 59322442: 709,
 31057580: 710,
 30259679: 711,
 49378947: 712,
 22660251: 713,
 15178539: 714,
 51693769: 715,
 47957873: 716,
 45353478: 717,
 46145280: 718,
 36944074: 719,
 40728307: 720,
 17611911: 721,
 33887035: 722,
 27202515: 723,
 34428487: 724,
 53871327: 725,
 52845738: 726,
 26716516: 727,
 48430961: 728,
 56913649: 729,
 53094748: 730,
 23881452: 731,
 55095433: 732,
 45767122: 733,
 31867071: 734,
 3607800: 735,
 54240496: 736,
 37524679: 737,
 35418460: 738,
 53678898: 739,
 56929016: 740,
 51582608: 741,
 57174415: 742,
 22271600: 743,
 36249004: 744,
 49609270: 745,
 49026612: 746,
 53232313: 747,
 6291687: 748,
 14443748: 749,
 59139742: 750,
 52516307: 751,
 49483893: 752,
 60599343: 753,
 24403886: 754,
 51692618: 755,
 39108918: 756,
 57592782: 757,
 57558523: 758,
 46937733: 759,
 60380995: 760,
 7919115: 761,
 22717807: 762,
 39445181: 763,
 59353518: 764,
 47515691: 765,
 57116626: 766,
 34504759: 767,
 6010062: 768,
 33386934: 769,
 4383759: 770,
 52774593: 771,
 60800972: 772,
 37893651: 773,
 19788663: 774,
 3980249: 775,
 56478493: 776,
 37583834: 777,
 58097428: 778,
 22734972: 779,
 23963754: 780,
 1744718: 781,
 46592872: 782,
 46362557: 783,
 52406868: 784,
 15506458: 785,
 30255206: 786,
 48871095: 787,
 22824441: 788,
 44949448: 789,
 42020805: 790,
 41897133: 791,
 37413896: 792,
 10061323: 793,
 39656517: 794,
 37674818: 795,
 46006855: 796,
 52988375: 797,
 53115770: 798,
 48191236: 799,
 36140576: 800,
 2997658: 801,
 16397345: 802,
 27194745: 803,
 57562041: 804,
 40296656: 805,
 46912125: 806,
 24032262: 807,
 42004315: 808,
 34577273: 809,
 49966405: 810,
 38322119: 811,
 51101882: 812,
 39612623: 813,
 60201045: 814,
 1180993: 815,
 28145685: 816,
 20026879: 817,
 54146297: 818,
 46397389: 819,
 21454461: 820,
 19512872: 821,
 9711936: 822,
 46188856: 823,
 19990411: 824,
 59996314: 825,
 17790971: 826,
 60438510: 827,
 48475672: 828,
 35833388: 829,
 50422005: 830,
 28238211: 831,
 40431121: 832,
 44316986: 833,
 47428232: 834,
 36283640: 835,
 11274688: 836,
 40101287: 837,
 46475910: 838,
 2795618: 839,
 34554729: 840,
 37967693: 841,
 52152127: 842,
 60117846: 843,
 2672453: 844,
 37799261: 845,
 42563931: 846,
 37064132: 847,
 46862510: 848,
 59598701: 849,
 21977659: 850,
 48674675: 851,
 36144534: 852,
 18381108: 853,
 39816390: 854,
 24000946: 855,
 42131176: 856,
 37021913: 857,
 1964379: 858,
 53590486: 859,
 48937101: 860,
 45525406: 861,
 60680011: 862,
 16370576: 863,
 60069040: 864,
 44636578: 865,
 46239553: 866,
 57230032: 867,
 44072741: 868,
 6590183: 869,
 59288122: 870,
 14026215: 871,
 56675543: 872,
 59625014: 873,
 40115534: 874,
 31695154: 875,
 5428669: 876,
 49331500: 877,
 50730647: 878,
 50425871: 879,
 28522631: 880,
 59741505: 881,
 51386245: 882,
 25354349: 883,
 35821264: 884,
 52301924: 885,
 54174374: 886,
 58599432: 887,
 58934928: 888,
 2631703: 889,
 38113572: 890,
 56631742: 891,
 40198678: 892,
 45716329: 893,
 35133979: 894,
 37308262: 895,
 9310265: 896,
 47883121: 897,
 58144789: 898,
 13922243: 899,
 46597500: 900,
 59081081: 901,
 34786372: 902,
 58379593: 903,
 54146904: 904,
 58478288: 905,
 9024479: 906,
 28307303: 907,
 7285175: 908,
 59199124: 909,
 42653289: 910,
 57575249: 911,
 33037111: 912,
 34475471: 913,
 35281150: 914,
 50003894: 915,
 60503940: 916,
 19609613: 917,
 52968092: 918,
 58674936: 919,
 51656529: 920,
 5401177: 921,
 49316827: 922,
 40296938: 923,
 55069109: 924,
 38751590: 925,
 57427611: 926,
 40560792: 927,
 49902794: 928,
 49191974: 929,
 22116074: 930,
 41270369: 931,
 38644427: 932,
 22059594: 933,
 58802156: 934,
 43206684: 935,
 46084873: 936,
 45256225: 937,
 10750409: 938,
 47769216: 939,
 38335189: 940,
 49148138: 941,
 5313327: 942,
 295633: 943,
 59943650: 944,
 30939503: 945,
 8742811: 946,
 22482101: 947,
 26171099: 948,
 56835519: 949,
 48312388: 950,
 38727191: 951,
 59329811: 952,
 42263318: 953,
 34274326: 954,
 37963152: 955,
 36686677: 956,
 50785237: 957,
 58952904: 958,
 50543954: 959,
 48157244: 960,
 46298140: 961,
 2041426: 962,
 15414013: 963,
 53296498: 964,
 34605051: 965,
 52107231: 966,
 27530980: 967,
 49918505: 968,
 40396329: 969,
 57763705: 970,
 40096879: 971,
 56606355: 972,
 22010283: 973,
 33239545: 974,
 6014503: 975,
 28438507: 976,
 19923648: 977,
 54579558: 978,
 17215228: 979,
 41100395: 980,
 59630679: 981,
 50683930: 982,
 44355303: 983,
 29833830: 984,
 43875129: 985,
 36985323: 986,
 35642826: 987,
 41128392: 988,
 45110516: 989,
 45707226: 990,
 47815104: 991,
 51578858: 992,
 50273145: 993,
 36501185: 994,
 43227872: 995,
 49315482: 996,
 59500288: 997,
 46865104: 998,
 '손정용': 999}

In [42]:
len(title_to_idx) #24079개 노래

24079

In [43]:
user_to_idx['손정용'] #내 고유번호

999

In [44]:
data3=data2
data3['user_id']=data3['user_id'].map(user_to_idx.get)
data3['title_artist']=data3['title_artist'].map(title_to_idx.get)
data3

    user_id  title_artist  quantity
0         0             0         1
1         0             1         1
2         0             2         1
3         0             3         1
4         0             4         1
..      ...           ...       ...
15      999          7837         1
16      999          7795         1
17      999           625         1
18      999          2118         1
19      999           667         1

[169967 rows x 3 columns]

In [45]:
from scipy.sparse import csr_matrix

csr_data = csr_matrix((data3.quantity, (data3.user_id, data3.title_artist)))
csr_data

<1000x24079 sparse matrix of type '<class 'numpy.int64'>'
	with 164186 stored elements in Compressed Sparse Row format>

In [46]:
# Sparsity: 얼마나 비어있나?
matrix_size = csr_data.shape[0]* csr_data.shape[1]
num_like =len(csr_data.nonzero()[0])
sparsity = 100 * (1 - (num_like / matrix_size))
sparsity

99.31813613522155

In [47]:
from implicit.als import AlternatingLeastSquares
import numpy as np

In [48]:
# Implicit AlternatingLeastSquares 모델의 선언
# 1. factors : 유저와 아이템의 벡터를 몇 차원으로 할 것인지
# 2. regularization : 과적합을 방지하기 위해 정규화 값을 얼마나 사용할 것인지 
# 3. use_gpu : GPU를 사용할 것인지 
# 4. iterations : epochs와 같은 의미입니다.
als_model = AlternatingLeastSquares(factors=100, regularization=0.1, use_gpu=False, iterations=15, dtype=np.float32)

C:\Users\jungy\anaconda3\lib\site-packages\implicit\utils.py:33: UserWarning: Intel MKL BLAS detected. Its highly recommend to set the environment variable 'export MKL_NUM_THREADS=1' to disable its internal multithreading
  warnings.warn(

In [49]:
# 모델 훈련
als_model.fit(csr_data)

  0%|          | 0/15 [00:00<?, ?it/s]

In [50]:
# 비슷한 노래 찾기
def get_similar_music(favorite_music):
    similar_music=[]
    title_id = title_to_idx[favorite_music]
    ids, scores = als_model.similar_items(title_id, N=20)
    for pair in zip(ids, scores):
        similar_music.append(pair)
    idx_to_title = {v:k for k,v in title_to_idx.items()}
    
    return [idx_to_title[i[0]] for i in similar_music]

In [68]:
get_similar_music('사랑하기 때문에_유재하')

['사랑하기 때문에_유재하',
 '지난날_유재하',
 '환생_윤종신',
 '편지_김광진',
 '비처럼 음악처럼_김현식',
 '오래전 그날_윤종신',
 '언젠가는_이상은 (=Lee-tzsche)',
 '슬픈 인연_Nami (나미)',
 'International Love Song_검정치마',
 '죽여줘_보수동쿨러',
 '입영열차안에서_김민우',
 '우리들의 사랑_유재하',
 '보이지 않는 사랑_신승훈',
 '우리의 밤은 당신의 낮보다 아름답다_코나',
 '모르겠어_어반자카파',
 '사랑했던 우리가 어떻게 친구가 되니_송하예',
 '내게 남은 사랑을 드릴께요_장혜리',
 '아이스크림 사랑_임병수',
 '31_카더가든',
 '기억의 습작_전람회']

In [53]:
# 노래 추천
def get_recommendations(your_name):
    user = user_to_idx[your_name]
    recommendations=[]
    ids, scores = als_model.recommend(user, csr_data[user], N=20)
    for pair in zip(ids, scores):
        recommendations.append(pair)
    idx_to_title = {v:k for k,v in title_to_idx.items()}
    
    return [idx_to_title[i[0]] for i in recommendations]

In [56]:
get_recommendations('손정용')

['봄여름가을겨울 (Still Life)_BIGBANG (빅뱅)',
 '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지_AKMU (악뮤)',
 'Blueming_아이유',
 'LOVE DIVE_IVE (아이브)',
 '정이라고 하자 (Feat. 10CM)_BIG Naughty (서동현)',
 'Yet To Come_방탄소년단',
 'Permission to Dance_방탄소년단',
 'Next Level_aespa',
 '겨울잠_아이유',
 'Off My Face_Justin Bieber',
 'ELEVEN_IVE (아이브)',
 "That's Hilarious_Charlie Puth",
 'Stuck with U_Ariana Grande',
 'Maniac_Conan Gray',
 'STAY_The Kid LAROI',
 'INVU_태연 (TAEYEON)',
 'Celebrity_아이유',
 'TOMBOY_(여자)아이들',
 '드라마_아이유',
 '회전목마 (Feat. Zion.T, 원슈타인) (Prod. Slom)_sokodomo']